---
- name: install db apt requirements
  become: yes
  apt:
    name: mysql-server

- name: push mysqld config
  become: yes
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    mode: 0644

- name: restart mysql server
  become: yes
  service:
    name: mysql
    state: restarted

- name: create mysql db and user
  become: yes
  shell: |
    mysql -e "create database if not exists test"
    mysql -e "use test;drop table if exists demo;create table demo (demo_id int not null auto_increment, demo_title varchar(100) not null, demo_body varchar(100) not null, primary key (demo_id) );"
    mysql -e "use test;insert into demo (demo_title,demo_body) values ('First Post','Hello world from {{ ansible_facts['nodename'] }}');"
    mysql -e "use test;insert into demo (demo_title,demo_body) values ('Second Post Post','Another post from {{ ansible_facts['nodename'] }}');"
    mysql -e "create user if not exists '{{ ansible_user }}'@'%' identified by '{{ db_pass }}';"
    mysql -e "grant all privileges on test.* to '{{ ansible_user }}'@'%';"
    mysql -e "flush privileges;"


